name: Victoria Eke-Göransson Bonde
favicon: null
layout_spectrum: 0.584182012360543
typography_spectrum: 0.7368820358533412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12437386182136834
  lightness: 0.6198631320148706
  saturation: 0.6960421395488083
  rhythmicContrast: 0.7228573088068515
purpose: []
